version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports
